############################################################################
# testing/orthello/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = orthello
PRIORITY  = $(CONFIG_TESTING_ORTHELLO_PRIORITY)
STACKSIZE = $(CONFIG_TESTING_ORTHELLO_STACKSIZE)
MODULE    = $(CONFIG_TESTING_ORTHELLO)
MAINSRC   = orthello_main.c

include $(APPDIR)/Application.mk
